# ________________________________________________
#
#       ARCHIVO DE IDIOMA DE CHAMPION TICKETS
#
#  Aquí puedes personalizar los mensajes del bot
#
# ________________________________________________

general:
  cannot_self: "No puedes usar este comando contigo mismo."
  # Marcadores de posición disponibles: <role>
  no_role: "Requieres el rol <role> para usar este comando."
  not_set: "Esta opción no está configurada, no se puede restablecer."
  cmd_disabled: "Este comando está desactivado en este servidor."
  no_perm: "No tienes permisos para ejecutar este comando."
  usage: "Uso incorrecto. Formato: `<usage>`"
  ping_loading: "Calculando ping..."
  ping: "Tiempo activo: <uptime>, ping del bot: <bot>ms, ping API: <api>ms"
  auto_response: "Hola <user>, <response>."
  auto_announce: "<message>."
  cooldown: "Debes esperar <cooldown> para usar este comando nuevamente."
  invalid_cmd: "Comando no válido."
  no_commands: "No hay comandos en esta categoría."
  no_suggest: "El canal de sugerencias no está configurado."
  suggestions:
    accepted: "Sugerencia aceptada correctamente."
    denied: "Sugerencia rechazada correctamente."
    deleted: "Sugerencia eliminada correctamente."
    sent: "Tu sugerencia ha sido enviada."
    vote_yes: "Has votado a favor."
    vote_no: "Has votado en contra."
    vote_reset: "Tu voto ha sido restablecido."
    placeholder: "Selecciona una acción para esta sugerencia."
    decision:
      accept: "Aceptar"
      deny: "Rechazar"
      delete: "Eliminar"
    not_voted: "No puedes restablecer un voto que no has emitido."
    already_voted: "Ya votaste, restablece tu voto primero."
    decision_reason: "Se ha registrado el motivo de la decisión."
  paypal_cred: "Token de PayPal o ID de cliente inválido en config.yml."
  dm_closed: "Los mensajes directos están desactivados (tuyos o del destinatario)."
buttons:
  confirm_close: "Sí, cerrar"
  cancel_close: "No, mantener abierto"
  create: "Crear Ticket"
  close: "Cerrar Ticket"
  go_ticket: "Ir al Ticket"
  next: "Siguiente"
  previous: "Anterior"
  download: "Descargar"
  link: "Obtener Enlace"
  # Marcadores de posición disponibles: <count> (Tanto para yes_vote como para no_vote - Número de votos)
  yes_vote: "<count>"
  no_vote: "<count>"
  remove_vote: "Eliminar Voto"
  transcripts:
    download: "Descargar"
    view: "Ver"
  answer_questions: "Responder Preguntas #<page>"
  answered_all: "Todas respondidas"
  paypal: "Pagar"
  invoice: "Pagar Factura"
  quote: "Aceptar Cotización"
  withdraw_yes: "Aceptar Retiro"
  withdraw_no: "Rechazar Retiro"
  send_withdraw: "Solicitar Retiro"
  claim: "Reclamar Ticket"
  send_quote: "Enviar Cotización"
  reply_message: "Responder"
  message_client: "Contactar Cliente"
  cancel_review: "Cancelar Revisión"
  delete_ticket: "Eliminar Ticket"
  decline_quote: "Rechazar Cotización"
titles:
  help: "🚀 Menú de Ayuda"
  error: "Error"
  auto_response: "Respuesta Automática"
  auto_announce: "Anuncio Automático"
  closed_dm: "Gracias por contactarnos"
  answers: "Respuestas"
  # Marcadores de posición disponibles: <page> (Página actual), <max> (Número de páginas)
  questions: "Preguntas (<page>/<max>)"
  products: "Productos Disponibles"
  sugg_accepted: "Sugerencia Aceptada"
  sugg_denied: "Sugerencia Rechazada"
  sugg_label: "Texto de Sugerencia"
  setprofile: "Perfil Personalizado"
  notes: "Notas del Canal"
  review: "Evaluar Usuario"
  commission: "Nueva Comisión"
  quote: "Cotización"
  message_client: "Mensaje al Cliente"
  reply_comm: "Responder Mensaje"
  accept_reason: "Motivo de Aceptación"
  deny_reason: "Motivo de Rechazo"
  quote_decline_reason: "Motivo de Rechazo"
modals:
  placeholders:
    bio: "Escribe tu biografía aquí."
    paypal: "Ingresa tu correo de PayPal"
    hours: "Indica tu horario disponible"
    suggestion: "Escribe tu sugerencia"
    notes: "Añade una nota para este canal"
    review: "Califica al usuario (1-5 estrellas)"
    comment: "Añade un comentario"
    comm_price: "Precio solicitado"
    comm_time: "Tiempo estimado"
    comm_note: "Notas adicionales"
    message_client: "Escribe tu mensaje al cliente"
    reply_comm: "Escribe tu respuesta"
    decision: "Explica el motivo"
    portfolio: "Enlace a tu portafolio"
    quote_decline: "Razón del rechazo"
  # Títulos/Etiquetas
  labels:
    bio: "Biografía"
    paypal: "PayPal"
    hours: "Disponibilidad"
    notes: "Notas"
    comment: "Comentario"
    comm_price: "Precio"
    comm_time: "Tiempo"
    comm_note: "Notas"
    message_client: "Mensaje"
    reply_comm: "Respuesta"
    decision: "Motivo"
    portfolio: "Portafolio"
    quote_decline: "Razón"
ticket:
  already_open: "Ya tienes un ticket abierto. Ciérralo primero."
  have_in_sel: "Tienes un ticket pendiente de categoría. Ciérralo o selecciona una."
  no_category: "Categoría principal no configurada. No se puede abrir ticket."
  no_panel: "Canal del panel no configurado."
  no_transcript: "Canal para transcripciones no configurado."
  user_added: "<user> añadido al ticket."
  user_removed: "<user> eliminado del ticket."
  ticket_channel: "Este comando solo funciona en canales de tickets."
  close_confirmation: "¿Seguro que quieres cerrar el ticket? Confirma abajo."
  bl_role: "No puedes abrir tickets (rol en lista negra)."
  bl_user: "No puedes abrir tickets (usuario en lista negra)."
  ticket_created: "Hola <user>, tu ticket se creó en <channel>."
  time_expired: "Tiempo agotado, el ticket no se eliminará."
  ticket_deleted: "Ticket será eliminado en breve..."
  cancel_delete: "Eliminación cancelada."
  channel_topic: "Ticket de <author>."
  have_ticket_category: "Límite de tickets alcanzado en esta categoría."
  already_claimed: "Ticket ya reclamado."
  ticket_claimed: "Ticket reclamado por <user>"
  ticket_assigned: "Ticket asignado a <user> por <author>."
  invalid_category: "Categoría inválida."
  category_moved: "Ticket movido a <category> por <user>"
  not_separate: "'separate_categories' y 'category > status' deben estar activos."
  move_topic: "Ticket movido a <category> por <user>"
  closed_dm: "Gracias por contactarnos. Evalúa al vendedor con `-review`."
  loading_answers: "Cargando respuestas..."
  question_idle: "Tiempo para responder agotado."
  panel_created: "Panel de tickets creado."
  priority:
    changed: "Prioridad de <channel> cambiada a <priority>."
    invalid: "Prioridad inválida. Opciones: Baja, Normal, Alta, Urgente."
    list: "**Urgentes**:\n<urgent>\n\n**Altas**:\n<high>"
    no_high: "> Sin tickets de alta prioridad"
    no_urgent: "> Sin tickets urgentes"
  invalid_panel: "Categoría de ticket no existe."
  answered_set: "Preguntas respondidas. Haz clic para continuar."
  answered_all: "Todas las preguntas respondidas."
  transcript_prompt: "Ingresa código de acceso (escribe 'exit' para salir):"
  reask: "Proceso de preguntas reiniciado."
  not_answered: "Preguntas sin responder en este ticket."
  # Marcadores de posición disponibles: <user>, <startFormatted>, <endFormatted>, <start> & <end>
  not_available: "Hola <user>, horario de atención: <startFormatted> a <endFormatted>."
  creation: "Creación: "
  closing: "Cierre: "
  not_ticket: "Este canal no es un ticket."
  ticket_renamed: "<channel> renombrado a <name>"
  ticket_move_closed: "Ticket archivado (cerrado por <user>). Usa el botón para eliminarlo."
  answers_thread_name: "Respuestas"
  answers_sending: "Enviando respuestas..."
  transcripts_list: "Transcripciones para **ID <id>**:\n<transcripts>"
  no_transcript_found: "No hay transcripciones para ID `<id>`"
utility:
  getid: "ID de <type>: `<id>`."
  counters_started: "Creando contadores..."
  counters_created: "Contadores creados."
  claimed_counter: "Reclamados: <stats>"
  total_counter: "Totales: <stats>"
  opened_counter: "Abiertos: <stats>"
  counters_category: "Estadísticas"
  math_error: "Error en cálculo."
service:
  invalid_mail: "Correo inválido."
  no_review: "Revisión no encontrada."
  review_self: "No puedes evaluarte a ti mismo."
  status: "Estado cambiado a __<status>__."
  availability:
    available: "Disponible"
    unavailable: "No disponible"
  no_paypal: "PayPal no configurado."
  no_hours: "Horario no configurado."
  no_portfolio: "Portafolio no configurado."
  note_added: "Nota actualizada: `<note>`."
  note_reseted: "Nota restablecida."
  profile_updated: "Perfil actualizado."
  hours_added: "Disponibilidad actualizada: `<hours>`."
  hours_reseted: "Horario restablecido."
  paypal_added: "PayPal actualizado: `<paypal>`."
  paypal_reseted: "PayPal restablecido."
  bio_added: "Biografía actualizada: `<bio>`."
  bio_reseted: "Biografía restablecida."
  invalid_crypto: "Criptomoneda inválida."
  invalid_invoice: "ID de factura inválido."
  invalid_portfolio: "Portafolio inválido (muy largo o enlace incorrecto)."
  portfolio_added: "Portafolio actualizado: `<portfolio>`."
  portfolio_reseted: "Portafolio restablecido."
  reviews:
    rating: "Selecciona una calificación (1-5 ⭐) y luego un comentario."
    rating_dm: "Hola, tu ticket fue cerrado. Califica nuestro soporte (1-5 ⭐) o escribe 'cancel'."
    placeholder: "Selecciona calificación (1-5 ⭐) o cancela."
    sent: "¡Gracias! Revisión enviada."
    time: "Tiempo agotado. Proceso cancelado."
    cannot_review: "No puedes evaluar a este usuario."
    cancel: "Revisión cancelada."
    no_comment: "Sin comentario."
    stars:
      one: "⭐"
      two: "⭐⭐"
      three: "⭐⭐⭐"
      four: "⭐⭐⭐⭐"
      five: "⭐⭐⭐⭐⭐"
  commission:
    no_time_frame: "Sin plazo estimado."
    no_notes: "Sin notas."
    not_commission: "Este ticket no es una comisión o ya está completada."
    no_data: "Preguntas sin responder. No se puede cotizar."
    marked: "Comisión marcada como <status> por <user>."
    complete: "Comisión completada. <freelancer> recibió <currency><taxAmount> de <currency><fullAmount> (<percentage>%)."
    no_quote: "Cotización no aceptada. No se puede cambiar estado."
    quote_sent: "Cotización enviada."
    message_sent: "Mensaje enviado a <user> sobre Comisión <channel>."
    reply_sent: "Respuesta enviada a <user> sobre Comisión <channel>."
    commission_thread: "Comisión (#<id>)"
    quote_declined: "Cotización de <freelancer> rechazada."
    embed_resent: "Embed de comisión actualizado."
  # Marcadores de posición disponibles: <user>, <userId> & <balance>
  balance: "Saldo de <user>: $<balance>"
  invalid_amount: "Fondos insuficientes."
  invalid_withdraw: "Usuario sin fondos suficientes."
  withdraw_request: "Solicitud de retiro por $<amount> enviada. Fondos retenidos."
  withdraw_accepted: "Retiro de $<amount> de <user> aceptado. Envía el pago."
  withdraw_accepted_dm: "Hola <user>, tu retiro de $<amount> fue aceptado por <acceptedBy>."
  withdraw_denied: "Retiro de $<amount> de <user> rechazado."
  withdraw_denied_dm: "Hola <user>, tu retiro de $<amount> fue rechazado por <acceptedBy>."
  no_mail: "PayPal no configurado."
  no_withdraw_channel: "Canal de retiros no configurado. Contacta al staff."
  withdraw_reason: "Retiro solicitado por <user>"
  taxes_format: "<name> - <amount>"
  data_edited: "Datos de <target> editados."
  client_info: "Información de <user> `(<userId>)`\n\n>>> **Pedidos:** <orderCount>\n**Total gastado:** $<amountSpent>"
  price_edited: "Precio cambiado a <currencySymbol><amount> por <user>."
products:
  # Marcadores de posición disponibles: <file> (Nombre del archivo)
  download_get: "Descarga tu archivo (<file>):"
  # Marcadores de posición disponibles: <link> (Nombre del enlace)
  link_get: "Accede a tu enlace (<link>):"
  # Marcadores de posición disponibles: <file> (Nombre del archivo)
  download: "Descargar (<file>):"
  # Marcadores de posición disponibles: <link> (Nombre del enlace)
  link: "Ir a (<link>):"
  # Marcadores de posición disponibles: <role> (Lista de roles requeridos)
  roles: "Requieres el/los rol(es) <role> para este producto."
  permissions: "Permisos insuficientes."
  invalid_product: "Producto no existe."
  none_type: "Producto no descargable."
  error: "Error. Producto inválido o no existe."
  file_uploading: "Preparando archivo..."
sellix:
  invalid_key: "Clave API de Sellix inválida."
  no_id: "Pedido no encontrado."
  used_id: "ID de pedido ya verificado."
  # Marcadores de posición disponibles: <product> (Producto comprado), <roles> (Roles obtenidos)
  verified: "Vinculaste tu Discord con la compra de <product> en Sellix."
  no_product: "Producto no encontrado."
  no_roles: "No hay roles de verificación configurados."
tebex:
  no_id: "Transacción no encontrada."
  used_id: "ID de transacción ya usado."
  # Marcadores de posición disponibles: <packages> (Paquetes comprados), <roles> (Roles obtenidos)
  verified: "Vinculaste tu Discord con la compra de <packages> paquete(s) en Tebex."
  no_roles: "No hay roles de verificación configurados."
cstore:
  no_id: "Transacción no encontrada."
  used_id: "ID de transacción ya usado."
  # Marcadores de posición disponibles: <packages> (Paquetes comprados), <roles> (Roles obtenidos)
  verified: "Vinculaste tu Discord con la compra de <packages> paquete(s) en CraftingStore."
  no_roles: "No hay roles de verificación configurados."
  no_package: "Paquete no encontrado."
dashboard:
  title: "Panel de QuickLand Tickets"
  not_found: "Página no encontrada."
  forbidden: "Acceso denegado. Contacta al administrador."
  welcome: "Bienvenido. Inicia sesión con Discord."
  login: "Iniciar sesión"
  home: "Inicio"
  no_users: "Sin usuarios"
  no_tickets: "Sin tickets abiertos."
  no_transcripts: "Sin transcripciones."
  tickets_list: "Tickets"
  ticket_categories: "Categorías"
  panel_management: "Paneles"
  transcripts_list: "Transcripciones"
  no_logs: "Sin registros."
  profile: "Perfil"
  select_subcategory: "Selecciona subcategoría a editar"
  save_panel: "Guardar"
  send_panel: "Enviar"
  preview_panel: "Vista previa"
  navbar:
    home: "Inicio"
    ticketing: "Tickets"
    settings: "Configuración"
    logs: "Registros"
    invoice: "Facturas"
    profile: "Perfil"
    logout: "Cerrar sesión"
  titles:
    total: "Total tickets"
    income: "Ingresos"
    invoices: "Facturas pagadas"
    commissions: "Comisiones"
    members: "Miembros"
    dash_logs: "Registros"
    server_logs: "Registros del servidor"
    save: "Guardar"
    delete: "Eliminar"
    access: "Accesos"
    add: "Gestionar usuarios"
    current_users: "Usuarios"
    paypal: "PayPal"
    portfolio: "Portafolio"
    hours: "Horario"
    bio: "Biografía"
    rating: "Calificación"
    invoices_page: "Facturas"
    commands: "Comandos"
    config: "Configuración"
    general_config: "General"
    channels_config: "Canales"
    togglables: "Opciones"
    dash_access: "Acceso al panel"
    config_access: "Acceso a configuración"
    cmds_access: "Acceso a comandos"
    subcategories: "Subcategorías"
    questions: "Preguntas"
    tickets_chart: "Gráfico de tickets"
    opened_chart: "Abiertos"
    closed_chart: "Cerrados"
    members_chart: "Miembros"
    join_chart: "Nuevos"
    leave_chart: "Salidas"
  invoice:
    id: "ID"
    author: "Autor"
    user: "Usuario"
    amount: "Monto"
    date: "Fecha"
    actions: "Acciones"
    filter: "Filtrar"
  # Para poner palabras en negrita usa doble asterisco (**), para seminegrita usa signo igual (=)
  # Marcadores de posición disponibles: [DATE], [AUTHOR], [AUTHOR_ID], [USER], [USER_ID], [AMOUNT] (para balance_add & balance_remove),
  # [INVOICE_ID] & [INVOICE_AMOUNT] (para invoice_paid, invoice_created), [CHANNEL_ID], [CHANNEL_NAME], [CURRENCY],
  # [VALUE] & [OPTION] (Para Editar Configuración en Panel y Comandos Toggle) & [TICKET]
  logs:
    balance_add: "[DATE] **[AUTHOR]** añadió **[CURRENCY][AMOUNT]** a **[USER]**"
    balance_remove: "[DATE] **[AUTHOR]** removió **[CURRENCY][AMOUNT]** de **[USER]**"
    invoice_paid: "[DATE] Factura [INVOICE_ID] pagada por **[USER]** ([CHANNEL_NAME])"
    invoice_created: "[DATE] **[AUTHOR]** creó Factura [INVOICE_ID] para **[USER]**"
    ticket_add: "[DATE] **[USER]** añadido a Ticket [CHANNEL_NAME] por **[AUTHOR]**"
    ticket_remove: "[DATE] **[USER]** removido de Ticket [CHANNEL_NAME] por **[AUTHOR]**"
    ticket_create: "[DATE] Ticket creado por **[AUTHOR]** ([CHANNEL_NAME])"
    ticket_close: "[DATE] **[AUTHOR]** cerró Ticket **[TICKET]** ([CHANNEL_ID])"
    mark_complete: "[DATE] **[AUTHOR]** completó Comisión [CHANNEL_NAME] (#**[TICKET]**)"
    dash_added: "[DATE] **[AUTHOR]** dio acceso a **[USER]**."
    dash_removed: "[DATE] **[AUTHOR]** removió acceso de **[USER]**."
    dash_ticket_del: "[DATE] **[AUTHOR]** eliminó ticket **[TICKET]**"
    dash_balance_change: "[DATE] **[AUTHOR]** actualizó saldo de **[USER]** a **[CURRENCY][AMOUNT]**"
    dash_login: "[DATE] **[AUTHOR]** inició sesión"
    dash_logout: "[DATE] **[AUTHOR]** cerró sesión"
    dash_edit_cfg: "[DATE] **[AUTHOR]** editó **[OPTION]**"
    dash_toggle_cmd: "[DATE] **[AUTHOR]** cambió **[OPTION]** [VALUE]"